/*
 * Billingo API v3
 * This is a Billingo API v3 documentation. Our API based on REST software architectural style. API has resource-oriented URLs, accepts JSON-encoded request bodies and returns JSON-encoded responses. To use this API you have to generate a new API key on our [site](https://app.billingo.hu/api-key). After that, you can test your API key on this page.
 *
 * The version of the OpenAPI document: 3.0.14
 * Contact: hello@billingo.hu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.clientapi.billingo.api;

import com.clientapi.billingo.invoker.ApiException;
import com.clientapi.billingo.model.ClientErrorResponse;
import com.clientapi.billingo.model.ConversationRate;
import com.clientapi.billingo.model.Currency;
import java.time.LocalDate;
import com.clientapi.billingo.model.ServerErrorResponse;
import com.clientapi.billingo.model.SubscriptionErrorResponse;
import com.clientapi.billingo.model.TooManyRequestsResponse;
import com.clientapi.billingo.model.ValidationErrorResponse;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for CurrencyApi
 */
@Disabled
public class CurrencyApiTest {

    private final CurrencyApi api = new CurrencyApi();

    /**
     * Get currencies exchange rate.
     *
     * Return with the exchange value of given currencies.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getConversionRateTest() throws ApiException {
        Currency from = null;
        Currency to = null;
        LocalDate date = null;
        ConversationRate response = api.getConversionRate(from, to, date);
        // TODO: test validations
    }

}
