/*
 * Billingo API v3
 * This is a Billingo API v3 documentation. Our API based on REST software architectural style. API has resource-oriented URLs, accepts JSON-encoded request bodies and returns JSON-encoded responses. To use this API you have to generate a new API key on our [site](https://app.billingo.hu/api-key). After that, you can test your API key on this page.
 *
 * The version of the OpenAPI document: 3.0.14
 * Contact: hello@billingo.hu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.clientapi.billingo.api;

import com.clientapi.billingo.invoker.ApiException;
import com.clientapi.billingo.model.ClientErrorResponse;
import com.clientapi.billingo.model.DocumentBlockList;
import com.clientapi.billingo.model.DocumentBlockType;
import com.clientapi.billingo.model.ServerErrorResponse;
import com.clientapi.billingo.model.SubscriptionErrorResponse;
import com.clientapi.billingo.model.TooManyRequestsResponse;
import com.clientapi.billingo.model.ValidationErrorResponse;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for DocumentBlockApi
 */
@Disabled
public class DocumentBlockApiTest {

    private final DocumentBlockApi api = new DocumentBlockApi();

    /**
     * List all document blocks
     *
     * Returns a list of your document blocks. The document blocks are returned sorted by creation date, with the most recent document blocks appearing first.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listDocumentBlockTest() throws ApiException {
        Integer page = null;
        Integer perPage = null;
        DocumentBlockType type = null;
        DocumentBlockList response = api.listDocumentBlock(page, perPage, type);
        // TODO: test validations
    }

}
