/*
 * Billingo API v3
 * This is a Billingo API v3 documentation. Our API based on REST software architectural style. API has resource-oriented URLs, accepts JSON-encoded request bodies and returns JSON-encoded responses. To use this API you have to generate a new API key on our [site](https://app.billingo.hu/api-key). After that, you can test your API key on this page.
 *
 * The version of the OpenAPI document: 3.0.14
 * Contact: hello@billingo.hu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.clientapi.billingo.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.clientapi.billingo.invoker.JSON;

/**
 * LedgerNumberInformation
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-10-15T09:59:06.459642900+02:00[Europe/Budapest]")
public class LedgerNumberInformation {
  public static final String SERIALIZED_NAME_BEVETEL = "bevetel";
  @SerializedName(SERIALIZED_NAME_BEVETEL)
  private String bevetel;

  public static final String SERIALIZED_NAME_VEVO = "vevo";
  @SerializedName(SERIALIZED_NAME_VEVO)
  private String vevo;

  public static final String SERIALIZED_NAME_PENZTAR = "penztar";
  @SerializedName(SERIALIZED_NAME_PENZTAR)
  private String penztar;

  public static final String SERIALIZED_NAME_AFA = "afa";
  @SerializedName(SERIALIZED_NAME_AFA)
  private String afa;

  public LedgerNumberInformation() {
  }

  public LedgerNumberInformation bevetel(String bevetel) {
    
    this.bevetel = bevetel;
    return this;
  }

   /**
   * Get bevetel
   * @return bevetel
  **/
  @javax.annotation.Nullable
  public String getBevetel() {
    return bevetel;
  }


  public void setBevetel(String bevetel) {
    this.bevetel = bevetel;
  }


  public LedgerNumberInformation vevo(String vevo) {
    
    this.vevo = vevo;
    return this;
  }

   /**
   * Get vevo
   * @return vevo
  **/
  @javax.annotation.Nullable
  public String getVevo() {
    return vevo;
  }


  public void setVevo(String vevo) {
    this.vevo = vevo;
  }


  public LedgerNumberInformation penztar(String penztar) {
    
    this.penztar = penztar;
    return this;
  }

   /**
   * Get penztar
   * @return penztar
  **/
  @javax.annotation.Nullable
  public String getPenztar() {
    return penztar;
  }


  public void setPenztar(String penztar) {
    this.penztar = penztar;
  }


  public LedgerNumberInformation afa(String afa) {
    
    this.afa = afa;
    return this;
  }

   /**
   * Get afa
   * @return afa
  **/
  @javax.annotation.Nullable
  public String getAfa() {
    return afa;
  }


  public void setAfa(String afa) {
    this.afa = afa;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LedgerNumberInformation ledgerNumberInformation = (LedgerNumberInformation) o;
    return Objects.equals(this.bevetel, ledgerNumberInformation.bevetel) &&
        Objects.equals(this.vevo, ledgerNumberInformation.vevo) &&
        Objects.equals(this.penztar, ledgerNumberInformation.penztar) &&
        Objects.equals(this.afa, ledgerNumberInformation.afa);
  }

  @Override
  public int hashCode() {
    return Objects.hash(bevetel, vevo, penztar, afa);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LedgerNumberInformation {\n");
    sb.append("    bevetel: ").append(toIndentedString(bevetel)).append("\n");
    sb.append("    vevo: ").append(toIndentedString(vevo)).append("\n");
    sb.append("    penztar: ").append(toIndentedString(penztar)).append("\n");
    sb.append("    afa: ").append(toIndentedString(afa)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("bevetel");
    openapiFields.add("vevo");
    openapiFields.add("penztar");
    openapiFields.add("afa");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to LedgerNumberInformation
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!LedgerNumberInformation.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in LedgerNumberInformation is not found in the empty JSON string", LedgerNumberInformation.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!LedgerNumberInformation.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `LedgerNumberInformation` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("bevetel") != null && !jsonObj.get("bevetel").isJsonNull()) && !jsonObj.get("bevetel").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `bevetel` to be a primitive type in the JSON string but got `%s`", jsonObj.get("bevetel").toString()));
      }
      if ((jsonObj.get("vevo") != null && !jsonObj.get("vevo").isJsonNull()) && !jsonObj.get("vevo").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `vevo` to be a primitive type in the JSON string but got `%s`", jsonObj.get("vevo").toString()));
      }
      if ((jsonObj.get("penztar") != null && !jsonObj.get("penztar").isJsonNull()) && !jsonObj.get("penztar").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `penztar` to be a primitive type in the JSON string but got `%s`", jsonObj.get("penztar").toString()));
      }
      if ((jsonObj.get("afa") != null && !jsonObj.get("afa").isJsonNull()) && !jsonObj.get("afa").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `afa` to be a primitive type in the JSON string but got `%s`", jsonObj.get("afa").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!LedgerNumberInformation.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'LedgerNumberInformation' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<LedgerNumberInformation> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(LedgerNumberInformation.class));

       return (TypeAdapter<T>) new TypeAdapter<LedgerNumberInformation>() {
           @Override
           public void write(JsonWriter out, LedgerNumberInformation value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public LedgerNumberInformation read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of LedgerNumberInformation given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of LedgerNumberInformation
  * @throws IOException if the JSON string is invalid with respect to LedgerNumberInformation
  */
  public static LedgerNumberInformation fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, LedgerNumberInformation.class);
  }

 /**
  * Convert an instance of LedgerNumberInformation to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

