/*
 * Billingo API v3
 * This is a Billingo API v3 documentation. Our API based on REST software architectural style. API has resource-oriented URLs, accepts JSON-encoded request bodies and returns JSON-encoded responses. To use this API you have to generate a new API key on our [site](https://app.billingo.hu/api-key). After that, you can test your API key on this page.
 *
 * The version of the OpenAPI document: 3.0.14
 * Contact: hello@billingo.hu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.clientapi.billingo.model;

import com.clientapi.billingo.model.DocumentExportFilterExtra;
import com.clientapi.billingo.model.DocumentExportOtherOptions;
import com.clientapi.billingo.model.DocumentExportQueryType;
import com.clientapi.billingo.model.DocumentExportSortBy;
import com.clientapi.billingo.model.DocumentExportType;
import com.clientapi.billingo.model.PaymentMethod;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.LocalDate;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for CreateDocumentExport
 */
public class CreateDocumentExportTest {
    private final CreateDocumentExport model = new CreateDocumentExport();

    /**
     * Model tests for CreateDocumentExport
     */
    @Test
    public void testCreateDocumentExport() {
        // TODO: test CreateDocumentExport
    }

    /**
     * Test the property 'queryType'
     */
    @Test
    public void queryTypeTest() {
        // TODO: test queryType
    }

    /**
     * Test the property 'startDate'
     */
    @Test
    public void startDateTest() {
        // TODO: test startDate
    }

    /**
     * Test the property 'endDate'
     */
    @Test
    public void endDateTest() {
        // TODO: test endDate
    }

    /**
     * Test the property 'documentBlockId'
     */
    @Test
    public void documentBlockIdTest() {
        // TODO: test documentBlockId
    }

    /**
     * Test the property 'exportType'
     */
    @Test
    public void exportTypeTest() {
        // TODO: test exportType
    }

    /**
     * Test the property 'numberStartYear'
     */
    @Test
    public void numberStartYearTest() {
        // TODO: test numberStartYear
    }

    /**
     * Test the property 'numberStartSequence'
     */
    @Test
    public void numberStartSequenceTest() {
        // TODO: test numberStartSequence
    }

    /**
     * Test the property 'numberEndYear'
     */
    @Test
    public void numberEndYearTest() {
        // TODO: test numberEndYear
    }

    /**
     * Test the property 'numberEndSequence'
     */
    @Test
    public void numberEndSequenceTest() {
        // TODO: test numberEndSequence
    }

    /**
     * Test the property 'paymentMethod'
     */
    @Test
    public void paymentMethodTest() {
        // TODO: test paymentMethod
    }

    /**
     * Test the property 'sortBy'
     */
    @Test
    public void sortByTest() {
        // TODO: test sortBy
    }

    /**
     * Test the property 'otherOptions'
     */
    @Test
    public void otherOptionsTest() {
        // TODO: test otherOptions
    }

    /**
     * Test the property 'filterExtra'
     */
    @Test
    public void filterExtraTest() {
        // TODO: test filterExtra
    }

}
