/*
 * Billingo API v3
 * This is a Billingo API v3 documentation. Our API based on REST software architectural style. API has resource-oriented URLs, accepts JSON-encoded request bodies and returns JSON-encoded responses. To use this API you have to generate a new API key on our [site](https://app.billingo.hu/api-key). After that, you can test your API key on this page.
 *
 * The version of the OpenAPI document: 3.0.14
 * Contact: hello@billingo.hu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.clientapi.billingo.model;

import com.clientapi.billingo.model.Entitlement;
import com.clientapi.billingo.model.Vat;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for DocumentItem
 */
public class DocumentItemTest {
    private final DocumentItem model = new DocumentItem();

    /**
     * Model tests for DocumentItem
     */
    @Test
    public void testDocumentItem() {
        // TODO: test DocumentItem
    }

    /**
     * Test the property 'productId'
     */
    @Test
    public void productIdTest() {
        // TODO: test productId
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'netUnitAmount'
     */
    @Test
    public void netUnitAmountTest() {
        // TODO: test netUnitAmount
    }

    /**
     * Test the property 'quantity'
     */
    @Test
    public void quantityTest() {
        // TODO: test quantity
    }

    /**
     * Test the property 'unit'
     */
    @Test
    public void unitTest() {
        // TODO: test unit
    }

    /**
     * Test the property 'netAmount'
     */
    @Test
    public void netAmountTest() {
        // TODO: test netAmount
    }

    /**
     * Test the property 'grossAmount'
     */
    @Test
    public void grossAmountTest() {
        // TODO: test grossAmount
    }

    /**
     * Test the property 'vat'
     */
    @Test
    public void vatTest() {
        // TODO: test vat
    }

    /**
     * Test the property 'vatAmount'
     */
    @Test
    public void vatAmountTest() {
        // TODO: test vatAmount
    }

    /**
     * Test the property 'entitlement'
     */
    @Test
    public void entitlementTest() {
        // TODO: test entitlement
    }

    /**
     * Test the property 'comment'
     */
    @Test
    public void commentTest() {
        // TODO: test comment
    }

}
