/*
 * Billingo API v3
 * This is a Billingo API v3 documentation. Our API based on REST software architectural style. API has resource-oriented URLs, accepts JSON-encoded request bodies and returns JSON-encoded responses. To use this API you have to generate a new API key on our [site](https://app.billingo.hu/api-key). After that, you can test your API key on this page.
 *
 * The version of the OpenAPI document: 3.0.14
 * Contact: hello@billingo.hu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.clientapi.billingo.model;

import com.clientapi.billingo.model.Currency;
import com.clientapi.billingo.model.Discount;
import com.clientapi.billingo.model.DocumentForm;
import com.clientapi.billingo.model.DocumentLanguage;
import com.clientapi.billingo.model.PaymentMethod;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for PartnerCustomBillingSettings
 */
public class PartnerCustomBillingSettingsTest {
    private final PartnerCustomBillingSettings model = new PartnerCustomBillingSettings();

    /**
     * Model tests for PartnerCustomBillingSettings
     */
    @Test
    public void testPartnerCustomBillingSettings() {
        // TODO: test PartnerCustomBillingSettings
    }

    /**
     * Test the property 'paymentMethod'
     */
    @Test
    public void paymentMethodTest() {
        // TODO: test paymentMethod
    }

    /**
     * Test the property 'documentForm'
     */
    @Test
    public void documentFormTest() {
        // TODO: test documentForm
    }

    /**
     * Test the property 'dueDays'
     */
    @Test
    public void dueDaysTest() {
        // TODO: test dueDays
    }

    /**
     * Test the property 'documentCurrency'
     */
    @Test
    public void documentCurrencyTest() {
        // TODO: test documentCurrency
    }

    /**
     * Test the property 'templateLanguageCode'
     */
    @Test
    public void templateLanguageCodeTest() {
        // TODO: test templateLanguageCode
    }

    /**
     * Test the property 'discount'
     */
    @Test
    public void discountTest() {
        // TODO: test discount
    }

}
