/*
 * Billingo API v3
 * This is a Billingo API v3 documentation. Our API based on REST software architectural style. API has resource-oriented URLs, accepts JSON-encoded request bodies and returns JSON-encoded responses. To use this API you have to generate a new API key on our [site](https://app.billingo.hu/api-key). After that, you can test your API key on this page.
 *
 * The version of the OpenAPI document: 3.0.14
 * Contact: hello@billingo.hu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.clientapi.billingo.model;

import com.clientapi.billingo.model.Currency;
import com.clientapi.billingo.model.DocumentType;
import com.clientapi.billingo.model.PaymentMethod;
import com.clientapi.billingo.model.ReceiptInsertItemsInner;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ReceiptInsert
 */
public class ReceiptInsertTest {
    private final ReceiptInsert model = new ReceiptInsert();

    /**
     * Model tests for ReceiptInsert
     */
    @Test
    public void testReceiptInsert() {
        // TODO: test ReceiptInsert
    }

    /**
     * Test the property 'vendorId'
     */
    @Test
    public void vendorIdTest() {
        // TODO: test vendorId
    }

    /**
     * Test the property 'partnerId'
     */
    @Test
    public void partnerIdTest() {
        // TODO: test partnerId
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'emails'
     */
    @Test
    public void emailsTest() {
        // TODO: test emails
    }

    /**
     * Test the property 'blockId'
     */
    @Test
    public void blockIdTest() {
        // TODO: test blockId
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'paymentMethod'
     */
    @Test
    public void paymentMethodTest() {
        // TODO: test paymentMethod
    }

    /**
     * Test the property 'currency'
     */
    @Test
    public void currencyTest() {
        // TODO: test currency
    }

    /**
     * Test the property 'conversionRate'
     */
    @Test
    public void conversionRateTest() {
        // TODO: test conversionRate
    }

    /**
     * Test the property 'electronic'
     */
    @Test
    public void electronicTest() {
        // TODO: test electronic
    }

    /**
     * Test the property 'items'
     */
    @Test
    public void itemsTest() {
        // TODO: test items
    }

}
