/*
 * Billingo API v3
 * This is a Billingo API v3 documentation. Our API based on REST software architectural style. API has resource-oriented URLs, accepts JSON-encoded request bodies and returns JSON-encoded responses. To use this API you have to generate a new API key on our [site](https://app.billingo.hu/api-key). After that, you can test your API key on this page.
 *
 * The version of the OpenAPI document: 3.0.14
 * Contact: hello@billingo.hu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.clientapi.billingo.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ServerTime
 */
public class ServerTimeTest {
    private final ServerTime model = new ServerTime();

    /**
     * Model tests for ServerTime
     */
    @Test
    public void testServerTime() {
        // TODO: test ServerTime
    }

    /**
     * Test the property 'epoch'
     */
    @Test
    public void epochTest() {
        // TODO: test epoch
    }

    /**
     * Test the property 'formatted'
     */
    @Test
    public void formattedTest() {
        // TODO: test formatted
    }

    /**
     * Test the property 'w3c'
     */
    @Test
    public void w3cTest() {
        // TODO: test w3c
    }

    /**
     * Test the property 'timezone'
     */
    @Test
    public void timezoneTest() {
        // TODO: test timezone
    }

}
